services:
  base:
    image: node:16
    working_dir: /excalidraw
    volumes:
      # Mount local version of `excalidraw` code
      - type: bind
        source: ./
        target: /excalidraw
    env_file:
      - .env
    tty: true
    ports:
      - 80:80
      - 3000:3000
