name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        id: install
        run: |
          yarn

      - name: Build
        id: build
        if: steps.install.outcome == 'success'
        env:
          CI: false
          REACT_APP_LIBRARY_BACKEND: ${{ secrets.REACT_APP_LIBRARY_BACKEND }}
          REACT_APP_LIBRARY_URL: ${{ secrets.REACT_APP_LIBRARY_URL }}
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
          REACT_APP_WS_SERVER_URL: ${{ secrets.REACT_APP_WS_SERVER_URL }}
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        if: steps.build.outcome == 'success'
        run: aws s3 sync ${PWD}/build ${{ secrets.STATIC_S3_BUCKET }}/${{ github.sha }}
